import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

// destructure children from parent component of layout
export const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + '- invoicing app' : 'invoice app'} </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col min-h-screen justify-between '>
        <header>
          <nav className='flex h-12 justify-between ites-center py-4 shadow-lg'>
            <Link href='/' className='text-md font bold'>
              Product Screen
            </Link>
            <div>
              <Link href='/cart'>
                <button className='p-2'>Cart</button>
              </Link>
              <Link href='/login'>
                {' '}
                <button className='p-2'>Login</button>
              </Link>
            </div>
          </nav>
        </header>
        {/* {children} is rendered here  */}
        <main className='container m-auto mt-4 px-4 '> {children}</main>
        <footer className='flex px-10 justify-center items-center'>
          <p>invoicing app with minimal footer </p>
        </footer>
      </div>
    </>
  )
}

// this component is the wrapper for all components
